### ISSUE TITLE
How to force VASP to print the Spin-spin contribution to zero-field splitting tensor (MHz) in OUTCAR

### ISSUE THREAD

**Issue by SAJALI** [alejandrogallo/dmatrix#1]
Dear
Fellow,
i was just curious how vasp prints Spin-spin contribution to zero-field splitting tensor (MHz) in OUTCAR
file to extract D-matrix information from, using d2E stuff you wrote, in first place. Any help would be appreciated.
Cheers

**Comment by RecursiveCarrot** [comment]
LDMATRIX   = .TRUE.

Basically isn't documented anywhere in the VASP manual. 
Bit late, but hope it helps.
